//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Inicio</summary>
	[PublishedModel("inicio")]
	public partial class Inicio : PublishedContentModel, IMenu
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		public new const string ModelTypeAlias = "inicio";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Inicio, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Inicio(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Imagen fondo header
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		[ImplementPropertyType("imagenFondoHeader")]
		public virtual global::Umbraco.Core.Models.MediaWithCrops ImagenFondoHeader => this.Value<global::Umbraco.Core.Models.MediaWithCrops>("imagenFondoHeader");

		///<summary>
		/// Lema
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		[ImplementPropertyType("lema")]
		public virtual string Lema => this.Value<string>("lema");

		///<summary>
		/// Listado Banners home
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		[ImplementPropertyType("listadoBannersHome")]
		public virtual global::Umbraco.Core.Models.Blocks.BlockListModel ListadoBannersHome => this.Value<global::Umbraco.Core.Models.Blocks.BlockListModel>("listadoBannersHome");

		///<summary>
		/// Listado promociones
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		[ImplementPropertyType("listadoPromociones")]
		public virtual global::Umbraco.Core.Models.Blocks.BlockListModel ListadoPromociones => this.Value<global::Umbraco.Core.Models.Blocks.BlockListModel>("listadoPromociones");

		///<summary>
		/// Nombre del sitio
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		[ImplementPropertyType("nombreDelSitio")]
		public virtual string NombreDelSitio => this.Value<string>("nombreDelSitio");

		///<summary>
		/// Titulo principal
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		[ImplementPropertyType("tituloPrincipal")]
		public virtual string TituloPrincipal => this.Value<string>("tituloPrincipal");

		///<summary>
		/// MostrarEnMenu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		[ImplementPropertyType("mostrarEnMenu")]
		public virtual bool MostrarEnMenu => global::Umbraco.Web.PublishedModels.Menu.GetMostrarEnMenu(this);

		///<summary>
		/// Nombre en menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.0")]
		[ImplementPropertyType("nombreEnMenu")]
		public virtual string NombreEnMenu => global::Umbraco.Web.PublishedModels.Menu.GetNombreEnMenu(this);
	}
}
